# Generated by Django 5.0.1 on 2024-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='isExist',
            field=models.BooleanField(default=True),
        ),
    ]
