# Generated by Django 5.0.1 on 2024-02-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_salesorder_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='isExist',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
